name: example
publish_to: 'none'

environment:
  sdk: '>=3.0.0'

scripts:
  generate-libraries: index_generator

dependencies:
  args:
  path:

dev_dependencies:
  build_runner: ^2.3.3
  index_generator:
    path: ../
