targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - cast_nullable_to_non_nullable

      json_serializable:
        options:
          any_map: true
          checked: true
          create_factory: true
          create_to_json: false
          disallow_unrecognized_keys: true
          explicit_to_json: false
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true

      index_generator:
        enabled: false

builders:
  index_generator:
    import: "package:index_generator/src/builder.dart"
    builder_factories: ["indexGeneratorBuilder"]
    build_extensions: { '$package$': ['.dart'] }
    auto_apply: none
    build_to: source
